# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [commit]

repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3.9127
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude:  >
          (?x)^(
          tests/testthat/.*/.*\.R(md|nw)?|
          vignettes/customizing_styler\.Rmd|
          tests/testthat/public-api/xyzfile-rnw/random4\.Rnw|
          vignettes/detect-alignment\.Rmd|
          tests/testmanual/addins/.*invalid.*|
          tests/testmanual/addins/r-valid\.R|
          )$
    -   id: roxygenize
        additional_dependencies:
        - r-lib/pkgapi
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          \.github/.*\.yaml|
          data/.*|
          tests/testthat/.*|
          touchstone/config\.json|
          (.*/|)\.Rprofile|
          (.*/|)\.Renviron|
          (.*/|)\.gitignore|
          (.*/|)NAMESPACE|
          (.*/|)WORDLIST|
          (.*/|)\.travis.yml|
          (.*/|)appveyor.yml|
          (.*/|)\.Rbuildignore|
          (.*/|)\.pre-commit-.*|
          .*\.[rR]|
          .*\.Rproj|
          .*\.py|
          .*\.feather|
          .*\.rds|
          .*\.Rds|
          .*\.sh|
          .*\.RData|
          .*-in_tree
          )$
    -   id: readme-rmd-rendered
    -   id: parsable-R
        exclude: >
          (?x)^(
          tests/testthat/public-api/xyzaddin/addin_region-.*|
          tests/testmanual/addins/r-invalid\.R|
          tests/testthat/escaping/basic-escape-out\.R|
          tests/testthat/indention_operators/.*pipe.*|
          tests/testthat/line_breaks_and_other/.*pipe.*|
          tests/testthat/exception_handling/parser-error.R|
          )$
    -   id: no-browser-statement
        exclude: >
          (?x)^(
          tests/testthat/public-api/xyzaddin/addin_region-.*|
          tests/testmanual/addins/r-invalid\.R|
          tests/testthat/escaping/basic-escape-out\.R|
          tests/testthat/indention_operators/.*pipe.*|
          tests/testthat/line_breaks_and_other/.*pipe.*|
          tests/testthat/exception_handling/parser-error.R|
          )$
    -   id: deps-in-desc
        exclude: >
          (?x)^(
          touchstone/.*|
          tests/testmanual/addins/.*invalid.*|
          tests/testthat/escaping/basic-escape-out\.R|
          tests/testthat/rnw/011-conditional-eval-out\.Rnw|
          tests/testthat/.*\.R(md)?
          )$
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: >
          (?x)^(
          \.Rd|
          tests/testthat/exception_handling/empty_file\.R|
          tests/testthat/parse_comments/eol_eof_spaces-.*|
          tests/testthat/reference-objects/.*|
          )$
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
    -   id: require-news-on-push
        name: Require bullet in NEWS.md
        description: NEWS.md must be updated with every PR.
        entry: inst/hooks/require-news-update.R
        stages: [push]
        language: script
        always_run: true
